version: "3.2"
services:
  mongo:
    image: mongo:4.4.4
    container_name: gestionadherentbdd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongoimport:
    image: mongo:4.4.4
    depends_on:
      - mongo
    volumes:
      - ./data:/data
      - ./import-data.sh:/docker-entrypoint-initdb.d/import-data.sh
    command: [ "/bin/bash", "/docker-entrypoint-initdb.d/import-data.sh" ]
    environment:
      - WAIT_HOSTS=mongo:27017

  rs1:
    image: mongo:4.4.4
    container_name: rs1
    volumes:
      - rs1:/data/db
    ports:
      - "27011:27017"
    command: mongod --replSet rs0 --bind_ip_all --port 27017

  rs2:
    image: mongo:4.4.4
    container_name: rs2
    volumes:
      - rs2:/data/db
    ports:
      - "27012:27017"
    command: mongod --replSet rs0 --bind_ip_all --port 27017

  rs3:
    image: mongo:4.4.4
    container_name: rs3
    volumes:
      - rs3:/data/db
    ports:
      - "27013:27017"
    command: mongod --replSet rs0 --bind_ip_all --port 27017

  init-replica-set:
    image: mongo:4.4.4
    container_name: init-replica-set
    depends_on:
      - rs1
      - rs2
      - rs3
    volumes:
      - ./init-replica-set.sh:/init-replica-set.sh
    command: [ "/bin/bash", "/init-replica-set.sh" ]
    networks:
      - default

volumes:
  mongodb_data:
  rs1:
  rs2:
  rs3: